name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: update GCC
      run: sudo apt-get update && sudo apt-get install gcc-9 g++-9
    - name: make
      run: CC=gcc-9 CXX=g++-9 make
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: qdl
        path: build/qdl
